start-at-login = true

[gaps]

inner.vertical = 4
inner.horizontal = 4
outer.top = 4
outer.bottom = 4
outer.right = 4
outer.left = 4

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-k = 'focus up'
alt-j = 'focus down'
alt-l = 'focus right'
alt-h = 'focus left'
alt-shift-k = 'move up'
alt-shift-j = 'move down'
alt-shift-l = 'move right'
alt-shift-h = 'move left'
alt-shift-equal = 'resize smart +50'
alt-shift-minus = 'resize smart -50'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'
ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

alt-shift-semicolon = 'mode service'

[mode.service.binding]

ctrl-c = 'mode main'
esc = ['reload-config', 'mode main']

backspace = ['close-all-windows-but-current', 'mode main']

r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']

alt-shift-k = ['join-with up', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
alt-shift-h = ['join-with left', 'mode main']

[[on-window-detected]]

check-further-callbacks = true
run = 'layout floating'
