font_family                  JetBrains Mono
font_size                    16
disable_ligatures            always

cursor_shape                 block
cursor_blink_interval        0

foreground                   #CBCBC6
background                   #1D1D1D
selection_foreground         #CBCBC6
selection_background         #4C4748

cursor                       #CBCBC6
cursor_text_color            background

color0                       #292929
color1                       #C55350
color2                       #88984A
color3                       #E09A49
color4                       #628B9D
color5                       #B2719B
color6                       #759B95
color7                       #CBCBC6
color8                       #3B3939
color9                       #D47766
color10                      #9FB95E
color11                      #EFC05E
color12                      #93A7B3
color13                      #D191AF
color14                      #89B3B6
color15                      #DDDAD7

mark1_foreground             #212121
mark2_foreground             #212121
mark3_foreground             #212121
mark1_background             #89B3B6
mark2_background             #D191AF
mark3_background             #EFC05E

url_color                    #93A7B3

shell_integration            disabled
macos_show_window_title_in   window

include local.conf
